platform :ios, '8.0'
use_frameworks!

target 'amico' do

 pod 'DLRadioButton'
 pod 'TPKeyboardAvoiding'
 pod 'Material'
 pod 'MaterialKit', '~> 0.4'
 pod 'TTRangeSlider'
 pod 'ActionSheetPicker-3.0'
 pod 'TagListView', '~> 1.0'
 pod 'Alamofire'
 pod 'AlamofireObjectMapper'
 pod 'FXKeychain', '~> 1.5'
 pod 'SVProgressHUD'

end

